name: Build

on:
  pull_request:
    types:
      - opened
      - synchronize

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install
        run: yarn install --immutable --immutable-cache

      - name: Build
        run: yarn build
